# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sE6m2qhsr7qt6PyisxY7iOGBLgmdI2hl
"""



"""# **Task 1:Lists**"""

#create list of 10 integers
num = [32,12,34,54,23,12,3,44,5,32]
print(num)

#find and print the sum, maximum, and minimum

print('Sum',sum(num))
print('Max',max(num))
print('Min',min(num))

#add and remove element
num.append(100)
num.remove(32)
print("updated list: ",num)

#sort the list
#ascending
num.sort()
print('Sorted list: ',num)
#descending
num.reverse()
print('reverse list: ',num)

"""# **Task 2:Tuples**"""

#create a tuple
Fruits = ('apple', 'banana', 'cherry', 'mango', 'grape')
print(Fruits)
print('First element', Fruits[0])
print('Last element', Fruits[-1])

#error on updation
# Fruits.append('orange')
# print(Fruits)


#convert tuple in list and update
Fruits_list = list(Fruits)
Fruits_list.append('orange')
print(Fruits_list)

"""# **Task 3:Sets**"""

#Create sets
A={1,2,3,4,5}
B={2,3,4,5,6}

# Union, intersection, and difference
print('Union',A | B)
print('Intersection',A & B)
print('Difference',A - B)

"""# **Task 4:Dictionary**"""

#create a dictionary of Friends and their marks
Friend_marks = {
    'Ismail': 98,
    'Mohiz': 92,
    'Hammad': 78,
    'Hanif': 95,
    'Hamid': 88
}

#print the Key and values
print('key',Friend_marks.keys())
print('Values',Friend_marks.values())

#update value
Friend_marks['Hammad']=85
print(Friend_marks)

"""# **Task 5: Numpy**

# **Task 6:Matplolib**
"""